version: '3.8'

services:
  web:
    container_name: paw-track
    build: .
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/1

  redis:
    container_name: paw-track-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis:/data
